config/routes.rb
LocalLabs::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :users do
    resources :permissions
  end
  get "/url_details", to: 'users#url_details'
  get "/manage_views", to: 'pages#manage_views'
  get "/url_dashboard", to: 'views#url_dashboard'
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :accounts do
    resources :views
  end

  resources :views do
    member do
      get "/twitter_profile", to: 'views#twitter_profile'
      get "/dashboard", to: 'views#dashboard'
      get "/mentions", to: 'views#mentions'
      get "/daily_view_metrics", to: 'views#daily_view_metrics'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :permissions
  has_many :views, through: :permissions, source: :view
  scope :non_admin, -> { where("admin is false") }

  def admin?
    admin
  end

  def permissible?(params)
    admin? || permissions.where(view_id: params[:id]).present?
  end
end

app/views/pages/home.html.slim
span.logo
  span.local Local
  span.labs Labs

app/views/pages/manage_views.html.slim
h1 Manage Views

- if @users.any?

  div#views
    div#permissions
      ul
        -@accounts.each do |a|
          li.account
            = a.name
            ul
              - a.views.each do |v|
                li.view_check_box
                  = check_box_tag "view_ids[]", v.id
                  = v.name
      = select_tag :user_id, options_from_collection_for_select(@users, 'id', 'name')
      br

      = submit_tag "SAVE", id: "update_permissions"
- else
  h4
    | There are no Non-Admin Users