config/routes.rb
LocalLabs::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :users do
    resources :permissions
  end
  get "/url_details", to: 'users#url_details'
  get "/manage_views", to: 'pages#manage_views'
  get "/url_dashboard", to: 'views#url_dashboard'
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :accounts do
    resources :views
  end

  resources :views do
    member do
      get "/twitter_profile", to: 'views#twitter_profile'
      get "/dashboard", to: 'views#dashboard'
      get "/mentions", to: 'views#mentions'
      get "/daily_view_metrics", to: 'views#daily_view_metrics'
    end
  end
end

app/views/views/_form.html.slim
#lower_form
  = form_for @view, multipart: true do |f|
    - if @view.account_id && @view.new_record?
      = f.hidden_field :account_id, value: @view.account_id
    -else
      .fieldset
        = f.label :account_id
        = f.select :account_id, options_from_collection_for_select(Account.all, 'id', 'name', @view.account_id)
    .fieldset
      = f.text_field :name, :placeholder => 'Name'
    .fieldset
      = f.text_field :url, :placeholder => 'URL'
    .fieldset
      = f.text_field :twitter_handle, :placeholder => 'Twitter username'
    .fieldset
      = f.text_field :widget_id, :placeholder => 'Twitter widget ID'
    .fieldset
      = f.text_field :analytics_id, :placeholder => 'Google analytics ID'
    .fieldset
      = f.label :logo, 'View Logo File'
      = f.file_field :logo
    = f.submit :id => 'submit'

app/views/views/_mention.html.slim
li.h-entry.tweet.customisable-border
  .header
    = link_to (mention.published_at).strftime("%F"), "https://twitter.com/#{mention.user_handle}/status/#{mention.twitter_id}", class: 'u-url permalink customisable-highlight'
    .h-card.p-author
      = link_to("https://twitter.com/#{mention.user_handle}", class: 'u-url profile') do
        = image_tag(mention.user_image, class: 'u-photo avatar')
        span.full-name
          span.p-name.customisable-highlight
            b
              = mention.user_name
        span.p-nickname dir='ltr'
          |  @#{mention.user_handle}
  .e-entry-content
    p.e-entry-title
      = mention.body

app/views/views/_mentions.html.slim
div#twitter_mentions
  div#mention_header
    h1 Mentions
  div#mention_list
    - if @view.mentions.any?
      ol
        - @view.mentions.each do |mention|
          = render partial: 'mention', locals: { mention: mention }
    - else
      h5 No Mentions Found

app/views/views/_twitter.html.slim
= link_to "Tweets by @#{@view.twitter_handle}", "https://twitter.com/#{@view.twitter_handle}", 'data-widget-id' => @view.widget_id, class: "twitter-timeline"

javascript:
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

app/views/views/dev_url_dasboard_view.html.erb
<style type="text/css">
.metrics{
  font-weight: bold;
}
.inputs{
  background: linear-gradient(to bottom, #6db3f2 0%, #54a3ee 50%, #3690f0 51%, #1e69de 100%);
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#6db3f2', endColorstr='#1e69de',GradientType=0 );
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-size: 4em;
    font-weight: 200;
}
.frame_text{
    text-transform: uppercase;
    color: #979797;
}
.left{
  padding-left: 40px;
}
.heading{
  text-align: center;text-align: center; font-size: 18px; padding-bottom: 20px; color: #979797;
}
.text-clr{
  color: #979797;
}
</style>
<div class="heading">
<%=@view.name%> - <%=@name%>
</div>
<table id="agg_metrics" align="center">
<tbody>
    <tr class="metric">
    <td id="unique_readers_val" class="inputs"><%=@user_count%></td>
        <td id="stories_read_val" class="inputs left"><%=@page_view_count%></td>
    </tr>
    <tr class="metric_label text-clr frame_text" >
       <td>Unique Readers</td>
       <td class="left">Stories Read</td>
    </tr>
<tr class="spacer"></tr>
    <tr class="metric">
        <td id="pgs_per_session_val" class="inputs"><%=@pages_per_session%></td>
        <td id="avg_session_duration_val" class="inputs left"><%=@avg_session_duration%></td>
    </tr>
    <tr class="metric_label text-clr frame_text">
      <td>Pages / Session</td>
      <td class="left">Avg. Session Duration</td>
    </tr>
</tbody>
</table>

<script type="text/javascript">
$(function() {
  window.history.pushState(null, "", "url_dashboard");
});
</script>

app/views/views/edit.html.slim
h1
  | Edit #{@view.name}

= render partial: 'form'

app/views/views/new.html.slim
h1
  | New #{@view.account.name if @view.account} View

= render partial: 'form'

app/views/views/show.html.slim
.container
  header
    span#account
      - if @view.logo_url
        = image_tag @view.logo_url, class: 'view-logo'
      - else
        | #{@view.name}
    form#date_picker
      label for="start_date"
      input#start_date type="text" placeholder="Start Date: yyyy-mm-dd" value=@start_date
      | -
      label for="end_date"
      input#end_date type="text" placeholder="End Date: yyyy-mm-dd" value=@end_date
      input#view_id type="hidden" value=@view.id /
  div#top_third
    table#agg_metrics
      tr.metric
        td#stories_produced_val
        td#stories_read_val
      tr.metric_label
        td Unique Pages
        td Stories Read
      tr.spacer
      tr.metric
        td#pgs_per_session_val
        td#avg_session_duration_val
      tr.metric_label
        td Pages / Session
        td Avg. Session Duration
      tr.spacer
      tr.metric
        td#unique_readers_val
      tr.metric_label
        td Unique Readers
    div.twitter_feed
      = link_to 'View Twitter Profile →', twitter_profile_view_path(@view), class: 'twitter-profile-link' if @view.twitter_handle
      = render partial: 'twitter' if @view.widget_id
      br
      div#twitter_mentions
        div#mention_header
          h1 Mentions
        div#mention_list
  
  div#middle_third
    table
      tr.section_title
        td
          | Visitor Profile
          br
          = select_tag(:collection, options_for_select(["Acquisition", "City", "User Type", "Referral"]))
        td.middle_label
          | Key Visitor Domains
      tr.middle_data
        td#visitor_profile
          svg#inner_circle
        td
          div#domain_cloud
  div#bottom_third
    h4.section_title Top Stories
    h5.subtitle By Page Views
    svg#page_views

app/views/views/twitter_profile.html.slim
h1
  | @#{@view.twitter_handle} Twitter Profile

form#twitter-date-picker
  label for="start_date"
  input#start_date type="text" placeholder="Start Date: yyyy-mm-dd" value=@start_date
  | -
  label for="end_date"
  input#end_date type="text" placeholder="End Date: yyyy-mm-dd" value=@end_date

#twitter-profile
  #stream
    = render partial: 'twitter' if @view.widget_id
  div#twitter_mentions
    div#mention_header
      h1
        | Mentions: 
        span#mention-count 0
    div#mention_list

app/views/views/url_dashboard.html.erb
<style type="text/css">
.metrics{
  font-weight: bold;
}
.inputs{
  background: linear-gradient(to bottom, #6db3f2 0%, #54a3ee 50%, #3690f0 51%, #1e69de 100%);
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#6db3f2', endColorstr='#1e69de',GradientType=0 );
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-size: 4em;
    font-weight: 200;
    border: none !important;
}
.frame_text{
    text-transform: uppercase;
    color: #979797;
}
.left{
  padding-left: 40px;
  border: none !important;
}
.heading{
  text-align: center;text-align: center; font-size: 18px; padding-bottom: 20px; color: #979797;
}
.text-clr{
  color: #979797;
}
table {
  border-collapse: collapse;
  color: #000;
}

td, th {
  border: 1px solid #999;
  padding: 0.5rem;
  text-align: left;
}
.story_details{
      margin-bottom: 3%;
}
</style>
<div class="heading">
<%=@view.name%> - <%=@pipeline.name%> <%#=@pipeline.api_id if !@pipeline.nil?%>

</div> 
<input type="hidden" id="api_id" value="<%=@pipeline.api_id%>">
<input type="hidden" id="view_id" value="<%=@view.id%>">

<table id="agg_metrics" align="center">
<tbody>
    <tr class="metric">
    <td id="unique_readers_val" class="inputs"><%=@user_count%></td>
        <td id="stories_read_val" class="inputs left"><%=@page_view_count%></td>
    </tr>
    <tr class="metric_label text-clr frame_text" >
       <td style="border: none !important;">Unique Readers</td>
       <td class="left">Stories Read</td>
    </tr>
<tr class="spacer"></tr>
    <tr class="metric">
        <td id="pgs_per_session_val" class="inputs"><%=@pages_per_session%></td>
        <td id="avg_session_duration_val" class="inputs left"><%=@avg_session_duration%></td>
    </tr>
    <tr class="metric_label text-clr frame_text">
      <td style="border: none !important;">Pages / Session</td>
      <td class="left">Avg. Session Duration</td>
    </tr>
</tbody>
</table>
<% story = Story.where("organization_id=?",@pipeline.api_id).map(&:story_id).uniq %>
<%i=1%>
<%if !story.nil? && story.count >= 1%>
  <table align="center" class="story_details">
    <thead>
    <tr style="background:#ff7e2e">
    <th>ID</th>
    <th>Story</th>
    <th>Views</th>
    </tr>
    </thead>
  <% story.each do |s| %>
   <% @dvpv = DailyViewPageView.where("permalink LIKE ? AND view_id = ? AND date >=  ? AND date <= ?","%#{s}%",@view.id, cookies[:start_date], cookies[:end_date] ).last %>
    <%if i <= 10 && !@dvpv.nil? && @dvpv.page_views > 0%>
    <% st = Story.where("story_id=?",s).last %>
    <tbody>
    <tr>
    <td><%=s%></td>
    <td><%=st.headline%></td>
    <td><%= @dvpv.page_views  if !@dvpv.nil?%></td>
    <input type="hidden" id="top_ban" value="10">
    <%i=i+1%>
    <%end%>
    <%end%>
    </tbody>
  </table>
<%end%>

 <script type="text/javascript">
$(function() {
  var api=$("#api_id").val();
  var view=$("#view_id").val();
  window.history.pushState(null, "", "url_dashboard?view_id="+view+"&org_id="+api);
  var topban = $("#top_ban").val();
  if(topban!=10){
  $(".story_details").hide();
  }
});
 </script>