config/routes.rb
LocalLabs::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :users do
    resources :permissions
  end
  get "/url_details", to: 'users#url_details'
  get "/manage_views", to: 'pages#manage_views'
  get "/url_dashboard", to: 'views#url_dashboard'
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :accounts do
    resources :views
  end

  resources :views do
    member do
      get "/twitter_profile", to: 'views#twitter_profile'
      get "/dashboard", to: 'views#dashboard'
      get "/mentions", to: 'views#mentions'
      get "/daily_view_metrics", to: 'views#daily_view_metrics'
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  self.primary_key = :id 
  validates_presence_of :name, :analytics_id
  validates_uniqueness_of :analytics_id
  has_many :views
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :require_login

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      flash[:notice] = "Account Created"
      redirect_to account_path(@account)
    else
      flash[:error] = "Account Not Created"
      render :new
    end
  end

  def show
    @account = Account.includes(:views).find(params[:id])
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(account_params)
      flash[:notice] = "Account Updated"
      redirect_to account_path(@account)
    else
      flash[:error] = "Account Not Updated"
      render :edit
    end
  end

  private
    
    def account_params
      params.require(:account).permit(:name, :analytics_id)
    end
end

app/views/accounts/_form.html.slim
#lower_form
  = form_for @account do |f|
    .fieldset
      = f.text_field :name, :autofocus => 'true', :placeholder => 'Name'
    .fieldset
      = f.text_field :analytics_id, :placeholder => 'Google Analytics ID'
    = f.submit :id => 'submit'

app/views/accounts/edit.html.slim
h1
  | Edit Account: #{@account.name}

= render partial: 'form'

app/views/accounts/new.html.slim
= render partial: 'form'

app/views/accounts/show.html.slim
h1
  | #{@account.name}

= link_to "New View", new_account_view_path(@account)